### ISSUE TITLE
Suggest batching data for writes in rishka_perror; loose fatherly advice to batch data in general

### ISSUE THREAD

**Issue by robertlipe** [nthnn/rishka#1]
https://github.com/nthnn/rishka/blob/6a92ab62954f06c21db48c3e19ba9c5014d7c4e0/src/rishka_errors.cpp#L22

I've not called out every occurrence of this in the code and I know that in panic()-style code it's tempting to handle byte writes as robotically as possible so you get every dying breath of debug info out, but generally you want to reduce the overhead of round-tripping to any system below you.

This code, for example, might benefit from

https://www.arduino.cc/reference/en/language/functions/communication/serial/write/

So 
```
void rishka_perror(const char* msg, uintptr_t len, bool flush) {
    if(len > 0 && msg)
        for(int i = 0; i < len; i++)
            Serial.write(msg[i]);

    if(flush) {
        Serial.println();
        Serial.flush();
    }
}
```
might become

```
void rishka_perror(const char* msg, uintptr_t len, bool flush) {
if (flush)
  Serial.println(str);
  Serial.flush();
} else {
  Serial.write(msg.len);
}
```

If this is in a templatable environment and flush is a constant (it almost always is) the optimizer may be able to remove the runtime test of flush totally and just replace your perror() with a calle to Serial.write(msg, len) so the correct message is passed through, though you might find the flexibility of making it more of a printf() call that evaluates arguments instead of a raw write() call that can potentially just load up a few pointers to the DMA engine and let your DMAC move it out.

But this specific call is a bit of overkill/distraction. The reaching point is that you want to batch those calls and deal in single calls with large (larger than a single byte) arguments instead of individual call/return sequences. Think "puts()" instead of "putc()". If the String returned by readString() already has a fast member that knows the length, don't  get the c_str() and then traverse THAT looking for that terminator.  (In some buffering system, getting the c_str itself can be costly if the buffers have to be coalesced.)  If write() is just doing a store (what about flow control?) this kind of thing is probably not totally hideous, but if you're packetizing that into a debug protocol by building up a remote debug packet or programming a DMA transfer for a UART or ethernet packet, it can easily be a thousand or more times the overhead.

Optimizing a crash error message on its own is dumb, but there were enough places in the code that processed data a byte at a time to make it seem worth typing this. When emulating a CPU, misspent clock cycles can sneak up on you quickly!

Save the pounds ounces at a time. If you're not from Myanmar, Liberia, or other Metric-impaired world, just translate that cliché from using "a lot" and "a little". :-)  Try to make function calls with batched values (std::spans, vector, etc.) instead of individual member/byte-level data if you at all can.

Cool project -  carry on!

**Comment by nthnn** [comment]
Hi! I've learned a lot from that upon reading, thank you. However, I admit I made a lot of mistake, even the very existence of `rishka_perror()` itself. As can be seen here:

https://github.com/nthnn/rishka/blob/6a92ab62954f06c21db48c3e19ba9c5014d7c4e0/src/rishka_errors.cpp#L31C1-L39C2

Only the `rishka_panic()` invokes/calls the `rishka_perror()` on this whole repository. I don't know what the f*** I was thinking when I wrote it. So, I removed `rishka_perror()` entirely, and changed `rishka_panic()` to:

https://github.com/nthnn/rishka/blob/dbc4ab891cd4490d276e74901991d1fb3d8551f6/src/rishka_errors.cpp#L20C1-L24C2

**Comment by robertlipe** [comment]
Cool. Hopeful that whole stream was taken as educational/PSA and not
insulting. Feel free to close as you see fit.

I hadn't even looked closely at the original panic(). You're right; that
was pretty goofy. :-)

i'm much happier with the latest version. That's much clearer now. Nice!

Thanx for humoring me. If you find the rest inspirational, groovy. If not,
just close them out.

Cool project!
RJL

**Comment by nthnn** [comment]
For me, it's so far from being an insult. I'm actually glad that I got some helpful feedbacks on this project of mine. Thanks again!

nthnn
